<?php

namespace AppBundle\Repository;

/**
 * BookmarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookmarkRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findByDates(){
        $em = $this->getEntityManager();
        return   $query = $em->createQuery(
            'SELECT b
        FROM AppBundle:Bookmark b
        ORDER BY b.createdAt DESC')
            ->getResult();
        }
}
