<?php

namespace AppBundle\Repository;

use Proxies\__CG__\AppBundle\Entity\User;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByUserID()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT r FROM AppBundle:Reservation r, AppBundle:User user  WHERE r.user = user.id '
            )
            ->getResult();
    }
    public function getReservations($order,$user,$status) {

        $qb = $this->createQueryBuilder("r");

                $qb->select("r");
    if($order != "none") {
                    $qb->orderBy("r." . $order, "DESC");
                }
                    
   if ($status !="all"){
       $qb->andWhere("r.status = :status")
       ->setParameter("status", $status);
   } 
   if($user!= "all") {
    $qb->leftJoin("r.user","user");
    $qb->andWhere("r.user = :user")->setParameter("user", $user);
}
   return $qb->getQuery()->getResult();
}
}