<?php

namespace AppBundle\Repository;

/**
 * Review
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends \Doctrine\ORM\EntityRepository
{  
    public function findByDates(){
    $em = $this->getEntityManager();
    return   $query = $em->createQuery(
        'SELECT rev
    FROM AppBundle:Review rev
    ORDER BY rev.createdat DESC')
        ->getResult();
    }
}
